---

- name: install nrpe for suse
  package:
    name:
      - nrpe
      - monitoring-plugins-common
      - monitoring-plugins-extras
      - monitoring-plugins-count_file
      - monitoring-plugins-disk
      - monitoring-plugins-load
      - monitoring-plugins-swap
      - monitoring-plugins-time
      - monitoring-plugins-ntp_peer
      - monitoring-plugins-ntp_time
      - monitoring-plugins-wl-files
      - monitoring-plugins-wl-dnsname
  register: nrpe_installed
  until: nrpe_installed is succeeded

...