---

- name: import vars for os family
  import_vars: '{{ ansible_os_family | lower }}.yml'

- name: import install playbook for os family
  import_playbook: 'install_{{ ansible_os_family | lower }}.yml'
  
- name: configure nrpe
  template:
    src: 'nrpe.cfg.j2'
    dest: '{{ nrpe_cfg_path }}'
    owner: 'nrpe'
    group: 'nrpe'
    mode: '0644'
  register: nrpe_configured

- name: restart nrpe service
  service:
    name: nrpe
    state: restarted
  when: nrpe_configured.changed

- name: enable nrpe service and assure it is started
  service:
    name: nrpe
    enabled: yes
    state: started
  tags:
    - service

...
